%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Implementation for:
%
%   Y. Gao, M. K. Ng, and C. Cui,
%   "Blind Hyperspectral and Multispectral Images Fusion: A Unified
%   Tensor Fusion Framework from Coupled Inverse Problem Perspective."
%
% Description:
%   This program provides an implementation of the blind hyperspectral
%   and multispectral image fusion method proposed in the above paper.
%
%   The Washington DC Mall hyperspectral image is used as the reference
%   ground-truth image. Based on this reference image, the program
%   simulates a pair of observed images with complementary spatial and
%   spectral resolutions:
%
%       1. A low-spatial-resolution hyperspectral image (LR-HSI);
%       2. A high-spatial-resolution multispectral image (HR-MSI).
%
%   The LR-HSI is generated by spatial blurring, downsampling, and adding
%   Gaussian noise, whereas the HR-MSI is generated by applying a spectral
%   response function and adding Gaussian noise.
%
%   The program then constructs the initial spatial degradation matrices
%   P1 and P2 and the initial spectral response matrix Pm. The function
%   InitialS_band is used to generate an initial estimate of the target
%   high-spatial-resolution hyperspectral image (HR-HSI). Finally, the
%   function ppl_ADMM_solver_8 is called to solve the proposed blind
%   hyperspectral–multispectral image fusion model using the partially
%   linearized alternating direction method of multipliers (ADMM).
%
% Main output:
%   SRI_tenfuse  - Reconstructed high-spatial-resolution hyperspectral image
%   time_tenfuse - Computational time of the proposed fusion algorithm
%
% Author:
%   Ying Gao
%
% Date:
%   July 10, 2025
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



clc; 
clear all; 
close all;
%% ======================== Load Real LR-HSI ==========================
addpath(genpath(cd));
load DC_mall.mat
load SRF_matrix.mat
SRI = HSI;
F = SRF';
[M,N,K] = size(SRI);
[rgb2] = func_hyperImshowR_2(SRI,[14,27,60]);
    
%% =================== generate Lr-HSI ====================
S_bar = hyperConvert2D(SRI);
downsampling_scale=4;
psf        =    fspecial('gaussian',9, 1);
par.fft_B      =    psf2otf(psf,[M N]);
par.fft_BT     =    conj(par.fft_B);
s0=1;
par.H          =    @(z)H_z(z, par.fft_B, downsampling_scale, [M N],s0 );
par.HT         =    @(y)HT_y(y, par.fft_BT, downsampling_scale,  [M N],s0);
Y_h_bar=par.H(S_bar);

  
SNRh=30;
sigma = sqrt(sum(Y_h_bar(:).^2)/(10^(SNRh/10))/numel(Y_h_bar));
rng(10,'twister')
   Y_h_bar = Y_h_bar+ sigma*randn(size(Y_h_bar));
   
HSI=hyperConvert3D(Y_h_bar,M/downsampling_scale, N/downsampling_scale );
HSI(HSI<0)=0;



%% ==============================  generate Hr-MSI ===================
rng(10,'twister')
Y = F*S_bar;
SNRm=35;
sigmam = sqrt(sum(Y(:).^2)/(10^(SNRm/10))/numel(Y));
Y = Y+ sigmam*randn(size(Y));
MSI=hyperConvert3D(Y,M,N);
MSI(MSI<0)=0;


[I,J,Km]    = size(MSI);
[Ih,Jh,K]   = size(HSI);

% MSI:
figure;
[rgb1] = func_hyperImshowR_2(MSI,[3,4,5]);

% HSI:
figure;
[rgb2] = func_hyperImshowR_2(HSI,[10,24,100]);


%% ================================ RUN Tenfuse =========================
%% Prepapring initial P1 and P2 and Pm 
    %%%% =============== P1 and P2 =================
    sig_h = 10;  
    ratio_h = 4;
    kernel_lengthh=9;
    %%%% Blur_kernel in original domain:
    %sig_h = (1/(2*(2.7725887)/ratio_h^2))^0.5; % STD of gaussian kernel
    BluKer_h_initial = fspecial('gaussian',[kernel_lengthh,kernel_lengthh],sig_h);
    blur1_spa_inter =sqrt(diag(BluKer_h_initial));
    blur1_spa = blur1_spa_inter/sum(blur1_spa_inter);
%    blur1_spa = blur1_spa_inter;
    blur1_spa = blur1_spa_inter;
    blur2_spa = blur1_spa;
    %%%% initial kernels in Fourier domain:
    blur1 = psf2otf(blur1_spa,[I 1]);
    blur2 = psf2otf(blur2_spa,[J 1]);
    %%%% initial Circulant matrix:
    F1 = dftmtx(I)/sqrt(I);
    B1_initial = F1*diag(blur1)*F1';
    B1_initial = real(B1_initial);
    B1_initial(B1_initial<1e-10)=0;
    F2 = dftmtx(J)/sqrt(J);
    B2_initial = F2*diag(blur2)*F2';
    B2_initial = real(B2_initial);
    B2_initial(B2_initial<1e-10)=0;    
    %%% Downsampling matrix:
    start_posh(1) = 4; % The starting point of downsampling
    start_posh(2) = 4; % The starting point of downsampling
    D1 = eye(I,I);
    D2 = eye(J,J);
    D1_spa = D1(start_posh:ratio_h:end,:);
    D2_spa = D2(start_posh:ratio_h:end,:);    
    %%% Degradation matrix:
    P1_initial = D1_spa*B1_initial;
    P2_initial = D2_spa*B2_initial;
    %%%% =========== Preparing initial point: Pm ===================
    %%%%% Sensor-informations-guided:
    I         = eye(K);     
    Dm_spe    = cell(1,8);
    Dm_spe{1} = I(9:17,:);
    Dm_spe{2} = I(15:31,:);
    Dm_spe{3} = I(31:42,:);
    Dm_spe{4} = I(46:52,:);
    Dm_spe{5} = I(66:70,:);
    Dm_spe{6} = I(110:124,:);
    Dm_spe{7} = I(139:143,:);
    Dm_spe{8} = I(25:51,:);

    %%%% Blur_kernels for each band of MSI:
    sig_m = 100;
    %%% b1:
    kernel_lengthm1 = size(Dm_spe{1},1);
    bluKer_m1 = fspecial('gaussian',[1 kernel_lengthm1],sig_m);   
    %%% b2:
    kernel_lengthm2 = size(Dm_spe{2},1);
    bluKer_m2 = fspecial('gaussian',[1 kernel_lengthm2],sig_m); 
    %%% b3:
    kernel_lengthm3 = size(Dm_spe{3},1);
    bluKer_m3 = fspecial('gaussian',[1 kernel_lengthm3],sig_m); 
    %%% b4:
    kernel_lengthm4 = size(Dm_spe{4},1);
    bluKer_m4 = fspecial('gaussian',[1 kernel_lengthm4],sig_m); 
    %%% b5:
    kernel_lengthm5 = size(Dm_spe{5},1);
    bluKer_m5 = fspecial('gaussian',[1 kernel_lengthm5],sig_m);   
    %%% b6:
    kernel_lengthm6 = size(Dm_spe{6},1);
    bluKer_m6 = fspecial('gaussian',[1 kernel_lengthm6],sig_m); 
    %%% b7:
    kernel_lengthm7 = size(Dm_spe{7},1);
    bluKer_m7 = fspecial('gaussian',[1 kernel_lengthm7],sig_m); 
    %%% b8:
    kernel_lengthm8 = size(Dm_spe{8},1);
    bluKer_m8 = fspecial('gaussian',[1 kernel_lengthm8],sig_m); 
    
     
    %%%% spectral response function:      
    Dm1  = Dm_spe{1};
    Dm2  = Dm_spe{2};
    Dm3  = Dm_spe{3};
    Dm4  = Dm_spe{4};
    Dm5  = Dm_spe{5};
    Dm6  = Dm_spe{6};
    Dm7  = Dm_spe{7};
    Dm8  = Dm_spe{8};

    %%%% give the space for the blur kernel for generating Pm:
    pm1_long  = sum(Dm1,1);
    nonzero_indices_m1 = double(find(pm1_long ~= 0));
    nonzero_indices{1} = nonzero_indices_m1;
    pm2_long  = sum(Dm2,1);
    nonzero_indices_m2 = double(find(pm2_long ~= 0));
    nonzero_indices{2} = nonzero_indices_m2;
    pm3_long  = sum(Dm3,1);
    nonzero_indices_m3 = double(find(pm3_long ~= 0));
    nonzero_indices{3} = nonzero_indices_m3;
    pm4_long  = sum(Dm4,1);
    nonzero_indices_m4 = double(find(pm4_long ~= 0));
    nonzero_indices{4} = nonzero_indices_m4;
    pm5_long  = sum(Dm5,1);
    nonzero_indices_m5 = double(find(pm5_long ~= 0));
    nonzero_indices{5} = nonzero_indices_m5;
    pm6_long  = sum(Dm6,1);
    nonzero_indices_m6 = double(find(pm6_long ~= 0));
    nonzero_indices{6} = nonzero_indices_m6;
    pm7_long  = sum(Dm7,1);
    nonzero_indices_m7 = double(find(pm7_long ~= 0));
    nonzero_indices{7} = nonzero_indices_m7;
    pm8_long           = sum(Dm8,1);
    nonzero_indices_m8 = double(find(pm8_long ~= 0));
    nonzero_indices{8} = nonzero_indices_m8;
    
    %%% Upating pm:
    pm1_long(nonzero_indices_m1) = bluKer_m1;
    pm2_long(nonzero_indices_m2) = bluKer_m2;
    pm3_long(nonzero_indices_m3) = bluKer_m3;
    pm4_long(nonzero_indices_m4) = bluKer_m4;
    pm5_long(nonzero_indices_m5) = bluKer_m5;
    pm6_long(nonzero_indices_m6) = bluKer_m6;
    pm7_long(nonzero_indices_m7) = bluKer_m7;
    pm8_long(nonzero_indices_m8) = bluKer_m8;
    %%% Updating Pm matrix:
    Pm(1,:) = pm1_long;
    Pm(2,:) = pm2_long;
    Pm(3,:) = pm3_long;
    Pm(4,:) = pm4_long;
    Pm(5,:) = pm5_long;
    Pm(6,:) = pm6_long;
    Pm(7,:) = pm7_long;
    Pm(8,:) = pm8_long;
   %% =================== Run pplADMM ==================== 
   tic;
   ratio = 4;
   lbd1  = 0.01;
   S_sharpened_bands = InitialS_band(MSI,HSI,ratio,lbd1);   
   S = InitialS_band(MSI,HSI,ratio,lbd1);
   %%%% parameters
        opts.lambda1   = 10; 
        opts.lambda2   = 0.1;
        opts.beta      = 10;
        opts.tol       = 1e-5;
        opts.mu        = 0.002;
        opts.max_iter  = 20;  
         SSs  = tens2mat(S,3);
        [UU,~,~]= svd(SSs,'econ');
        opts.nonzero_indices = nonzero_indices;
        opts.S_initial = S;
        opts.S_ideal   = SRI;
        opts.UU        = UU;
        opts.P1        = P1_initial;    
        opts.P2        = P2_initial;
        opts.Pm        = Pm; 
        opts.b1        = blur1_spa;
        opts.b2        = blur2_spa;
        opts.b31       = bluKer_m1';
        opts.b32       = bluKer_m2';
        opts.b33       = bluKer_m3';
        opts.b34       = bluKer_m4'; 
        opts.b35       = bluKer_m5';
        opts.b36       = bluKer_m6';
        opts.b37       = bluKer_m7';
        opts.b38       = bluKer_m8';
        opts.Dm_spe    = Dm_spe;
        opts.D1_spa    = D1_spa;
        opts.D2_spa    = D2_spa;
        opts.tau       = 1;
        [Outs_tenfuse] = ppl_ADMM_solver_8(MSI,HSI,opts);
        time_tenfuse = toc;        
        SRI_tenfuse = Outs_tenfuse.SRI;
        
        



